In [245]:
import pandas as pd
import numpy as np

In [246]:
df = pd.read_csv('fb.csv')

In [247]:
df.head()

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,139441,Photo,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640,119,4,79.0,17.0,100
1,139441,Status,2,12,3,10,0.0,10460,19057,1457,1361,1674,11710,6112,1108,5,130.0,29.0,164
2,139441,Photo,3,12,3,3,0.0,2413,4373,177,113,154,2812,1503,132,0,66.0,14.0,80
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
4,139441,Photo,2,12,2,3,0.0,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393

In [248]:
df.columns

Index(['Page total likes', 'Type', 'Category', 'Post Month', 'Post Weekday',
       'Post Hour', 'Paid', 'Lifetime Post Total Reach',
       'Lifetime Post Total Impressions', 'Lifetime Engaged Users',
       'Lifetime Post Consumers', 'Lifetime Post Consumptions',
       'Lifetime Post Impressions by people who have liked your Page',
       'Lifetime Post reach by people who like your Page',
       'Lifetime People who have liked your Page and engaged with your post',
       'comment', 'like', 'share', 'Total Interactions'],
      dtype='object')

In [249]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 19 columns):
Page total likes                                                       500 non-null int64
Type                                                                   500 non-null object
Category                                                               500 non-null int64
Post Month                                                             500 non-null int64
Post Weekday                                                           500 non-null int64
Post Hour                                                              500 non-null int64
Paid                                                                   499 non-null float64
Lifetime Post Total Reach                                              500 non-null int64
Lifetime Post Total Impressions                                        500 non-null int64
Lifetime Engaged Users                                                 500 non-null int64
Lifetime Post Consumers                                                500 non-null int64
Lifetime Post Consumptions                                             500 non-null int64
Lifetime Post Impressions by people who have liked your Page           500 non-null int64
Lifetime Post reach by people who like your Page                       500 non-null int64
Lifetime People who have liked your Page and engaged with your post    500 non-null int64
comment                                                                500 non-null int64
like                                                                   499 non-null float64
share                                                                  496 non-null float64
Total Interactions                                                     500 non-null int64
dtypes: float64(3), int64(15), object(1)
memory usage: 74.3+ KB

In [250]:
df.describe()

,Page total likes,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
count,500.000000,500.000000,500.000000,500.000000,500.000000,499.000000,500.00000,5.000000e+02,500.000000,500.000000,500.000000,5.000000e+02,500.000000,500.000000,500.00000,499.000000,496.000000,500.000000
mean,123194.176000,1.880000,7.038000,4.150000,7.840000,0.278557,13903.36000,2.958595e+04,920.344000,798.772000,1415.130000,1.676638e+04,6585.488000,609.986000,7.48200,177.945892,27.266129,212.120000
std,16272.813214,0.852675,3.307936,2.030701,4.368589,0.448739,22740.78789,7.680325e+04,985.016636,882.505013,2000.594118,5.979102e+04,7682.009405,612.725618,21.18091,323.398742,42.613292,380.233118
min,81370.000000,1.000000,1.000000,1.000000,1.000000,0.000000,238.00000,5.700000e+02,9.000000,9.000000,9.000000,5.670000e+02,236.000000,9.000000,0.00000,0.000000,0.000000,0.000000
25%,112676.000000,1.000000,4.000000,2.000000,3.000000,0.000000,3315.00000,5.694750e+03,393.750000,332.500000,509.250000,3.969750e+03,2181.500000,291.000000,1.00000,56.500000,10.000000,71.000000
50%,129600.000000,2.000000,7.000000,4.000000,9.000000,0.000000,5281.00000,9.051000e+03,625.500000,551.500000,851.000000,6.255500e+03,3417.000000,412.000000,3.00000,101.000000,19.000000,123.500000
75%,136393.000000,3.000000,10.000000,6.000000,11.000000,1.000000,13168.00000,2.208550e+04,1062.000000,955.500000,1463.000000,1.486050e+04,7989.000000,656.250000,7.00000,187.500000,32.250000,228.500000
max,139441.000000,3.000000,12.000000,7.000000,23.000000,1.000000,180480.00000,1.110282e+06,11452.000000,11328.000000,19779.000000,1.107833e+06,51456.000000,4376.000000,372.00000,5172.000000,790.000000,6334.000000

# CREATING DATA SUBSETS

In [251]:
df.iloc[1:10,:]

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
1,139441,Status,2,12,3,10,0.0,10460,19057,1457,1361,1674,11710,6112,1108,5,130.0,29.0,164
2,139441,Photo,3,12,3,3,0.0,2413,4373,177,113,154,2812,1503,132,0,66.0,14.0,80
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
4,139441,Photo,2,12,2,3,0.0,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393
5,139441,Status,2,12,1,9,0.0,10472,20849,1191,1073,1389,16034,7852,1016,1,152.0,33.0,186
6,139441,Photo,3,12,1,3,1.0,11692,19479,481,265,364,15432,9328,379,3,249.0,27.0,279
7,139441,Photo,3,12,7,9,1.0,13720,24137,537,232,305,19728,11056,422,0,325.0,14.0,339
8,139441,Status,2,12,7,3,0.0,11844,22538,1530,1407,1692,15220,7912,1250,0,161.0,31.0,192
9,139441,Photo,3,12,6,10,0.0,4694,8668,280,183,250,4309,2324,199,3,113.0,26.0,142

In [252]:
df.iloc[1:10,1:6]

     Type  Category  Post Month  Post Weekday  Post Hour
1  Status         2          12             3         10
2   Photo         3          12             3          3
3   Photo         2          12             2         10
4   Photo         2          12             2          3
5  Status         2          12             1          9
6   Photo         3          12             1          3
7   Photo         3          12             7          9
8  Status         2          12             7          3
9   Photo         3          12             6         10

In [253]:
df.iloc[20:30,[1,4,10,12]]

,Type,Post Weekday,Lifetime Post Consumers,Lifetime Post Impressions by people who have liked your Page
20,Photo,1,142,3561
21,Photo,7,15,2196
22,Link,7,104,6282
23,Photo,7,118,2964
24,Status,6,1270,9684
25,Status,6,1462,10266
26,Status,5,2531,17748
27,Photo,5,124,2612
28,Photo,5,559,9217
29,Video,4,1068,30131

In [254]:
df.iloc[[1,25,40,44,100,88],[1,3,5,7,9,11,13]]

,Type,Post Month,Post Hour,Lifetime Post Total Reach,Lifetime Engaged Users,Lifetime Post Consumptions,Lifetime Post reach by people who like your Page
1,Status,12,10,10460,1457,1674,6112
25,Status,12,3,8284,1521,1711,5372
40,Status,12,11,13280,2055,2720,9344
44,Photo,12,11,4284,355,513,3634
100,Photo,10,9,1357,37,55,1120
88,Photo,11,3,1531,212,1359,690

In [255]:
df.iloc[1:10,-4:]

   comment    like  share  Total Interactions
1        5   130.0   29.0                 164
2        0    66.0   14.0                  80
3       58  1572.0  147.0                1777
4       19   325.0   49.0                 393
5        1   152.0   33.0                 186
6        3   249.0   27.0                 279
7        0   325.0   14.0                 339
8        0   161.0   31.0                 192
9        3   113.0   26.0                 142

# MERGE DATA

In [256]:
df1 = pd.read_csv("newfb.csv")

In [257]:
df1.head()

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,136013,Status,2,10,5,3,0,8896,17202,1480,1426,1932,13838,7020,1292,0,129,25.0,154
1,136013,Photo,1,10,4,10,1,4018,8617,428,374,616,6677,2992,351,4,77,19.0,100
2,136013,Link,1,10,4,3,0,68992,229733,1032,975,1345,17842,8032,635,15,143,44.0,202
3,136013,Status,3,10,3,10,0,13152,25666,2543,2438,3179,20547,10280,2278,2,227,36.0,265
4,136013,Status,2,10,3,2,1,31136,59964,6164,5934,9237,35977,18048,4376,60,859,90.0,1009

In [258]:
df1.describe()

,Page total likes,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
count,134.000000,134.000000,134.000000,134.000000,134.000000,134.000000,134.000000,134.000000,134.000000,134.000000,134.000000,134.000000,134.000000,134.000000,134.000000,134.000000,133.000000,134.000000
mean,132805.373134,1.962687,8.171642,3.940299,7.395522,0.343284,14206.410448,28189.365672,996.059701,834.216418,1428.067164,15111.768657,7253.708955,723.388060,11.246269,239.268657,34.842105,285.097015
std,2490.393437,0.750005,1.051502,2.017820,3.988741,0.476587,22053.833469,47561.243647,1093.712748,900.632454,1953.129327,19860.937097,7763.722562,744.388551,35.274740,489.215886,71.460398,591.225615
min,128032.000000,1.000000,7.000000,1.000000,1.000000,0.000000,1006.000000,1594.000000,111.000000,90.000000,118.000000,1055.000000,651.000000,93.000000,0.000000,11.000000,1.000000,15.000000
25%,131300.000000,1.000000,7.000000,2.000000,3.000000,0.000000,3378.000000,5686.250000,429.750000,361.250000,526.000000,4084.500000,2263.500000,316.250000,2.000000,74.250000,11.000000,91.000000
50%,132509.000000,2.000000,8.000000,4.000000,9.000000,0.000000,5184.000000,9076.000000,600.000000,482.500000,726.000000,5901.500000,3252.000000,424.500000,4.000000,127.000000,22.000000,157.000000
75%,135195.000000,3.000000,9.000000,6.000000,10.000000,1.000000,15178.000000,32088.000000,1028.000000,902.000000,1385.000000,19551.500000,10358.000000,735.500000,9.000000,232.250000,40.000000,275.500000
max,136013.000000,3.000000,10.000000,7.000000,23.000000,1.000000,180480.000000,319133.000000,8072.000000,5934.000000,14974.000000,122474.000000,51456.000000,4376.000000,372.000000,5172.000000,790.000000,6334.000000

In [259]:
print(df.shape,df1.shape)

(500, 19) (134, 19)

In [260]:
df3 = df.append(df1,ignore_index=True)

In [261]:
df3

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,139441,Photo,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640,119,4,79.0,17.0,100
1,139441,Status,2,12,3,10,0.0,10460,19057,1457,1361,1674,11710,6112,1108,5,130.0,29.0,164
2,139441,Photo,3,12,3,3,0.0,2413,4373,177,113,154,2812,1503,132,0,66.0,14.0,80
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
4,139441,Photo,2,12,2,3,0.0,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393
5,139441,Status,2,12,1,9,0.0,10472,20849,1191,1073,1389,16034,7852,1016,1,152.0,33.0,186
6,139441,Photo,3,12,1,3,1.0,11692,19479,481,265,364,15432,9328,379,3,249.0,27.0,279
7,139441,Photo,3,12,7,9,1.0,13720,24137,537,232,305,19728,11056,422,0,325.0,14.0,339
8,139441,Status,2,12,7,3,0.0,11844,22538,1530,1407,1692,15220,7912,1250,0,161.0,31.0,192
9,139441,Photo,3,12,6,10,0.0,4694,8668,280,183,250,4309,2324,199,3,113.0,26.0,142
10,139441,Status,2,12,5,10,0.0,21744,42334,4258,4100,4540,37849,18952,3798,0,233.0,19.0,252
11,139441,Photo,2,12,5,10,0.0,3112,5590,208,127,145,3887,2174,165,0,88.0,18.0,106
12,139441,Photo,2,12,5,10,0.0,2847,5133,193,115,133,3779,2072,152,0,90.0,14.0,104
13,139441,Photo,2,12,5,3,0.0,2549,4896,249,134,168,3631,1917,183,5,137.0,10.0,152
14,138414,Photo,2,12,4,5,1.0,22784,39941,887,337,417,34415,19312,684,2,577.0,20.0,599
15,138414,Status,2,12,3,10,0.0,10060,19680,1264,1209,1425,17272,8548,1162,4,86.0,18.0,108
16,138414,Photo,3,12,3,3,0.0,1722,2981,163,123,148,1868,1050,123,2,40.0,12.0,54
17,138414,Photo,1,12,2,12,1.0,53264,111785,1706,1103,1655,92512,39776,1307,15,678.0,20.0,713
18,138414,Status,3,12,2,3,0.0,3930,7509,130,86,112,5009,2410,101,4,54.0,17.0,75
19,138414,Photo,3,12,1,11,0.0,1591,2825,121,88,111,2116,1161,100,0,34.0,8.0,42
20,138414,Photo,2,12,1,3,0.0,2848,5066,200,142,184,3561,1963,157,3,66.0,12.0,81
21,138414,Photo,1,12,7,10,0.0,1384,2467,15,15,20,2196,1172,15,0,0.0,0.0,0
22,138414,Link,1,12,7,10,0.0,3454,6853,118,104,130,6282,3100,106,0,16.0,2.0,18
23,138414,Photo,3,12,7,3,0.0,2723,4888,176,118,143,2964,1621,143,0,72.0,24.0,96
24,138414,Status,2,12,6,10,0.0,8488,15294,1341,1270,1489,9684,5244,995,3,99.0,19.0,121
25,138458,Status,2,12,6,3,0.0,8284,15104,1521,1462,1711,10266,5372,1200,0,88.0,18.0,106
26,138458,Status,2,12,5,11,0.0,19552,34143,2806,2531,3420,17748,9824,1779,10,412.0,72.0,494
27,138458,Photo,3,12,5,3,0.0,2478,4306,212,124,149,2612,1443,166,0,100.0,17.0,117
28,138895,Photo,2,12,5,3,0.0,9560,18264,973,559,885,9217,4748,621,36,523.0,63.0,622
29,138895,Video,1,12,4,11,1.0,36208,61262,1141,1068,1728,30131,14112,559,18,143.0,13.0,174
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
604,130791,Status,2,7,4,6,0.0,17360,33613,2573,2448,6017,23338,11800,1905,9,484.0,79.0,572
605,130791,Video,1,7,3,11,1.0,21872,40413,3872,3822,7327,24667,12920,2218,18,315.0,76.0,409
606,130791,Photo,2,7,3,5,1.0,180480,319133,8072,4010,6242,108752,51456,3316,372,5172.0,790.0,6334
607,130791,Photo,1,7,2,13,0.0,44464,66824,1052,930,1571,22904,14080,559,4,154.0,30.0,188
608,130791,Photo,2,7,2,8,0.0,2881,5188,550,503,730,3840,2040,323,0,73.0,15.0,88
609,129600,Photo,2,7,1,12,0.0,3460,6503,541,482,667,4371,2260,314,0,96.0,19.0,115
610,129600,Photo,3,7,1,6,0.0,3406,5656,571,512,731,4446,2598,355,1,98.0,19.0,118
611,129600,Photo,2,7,7,11,1.0,2602,4349,479,444,588,3342,1946,287,1,53.0,14.0,68
612,129600,Photo,1,7,7,6,1.0,5848,9068,622,570,795,6651,4212,383,4,71.0,10.0,85
613,129600,Photo,1,7,6,11,0.0,26944,43464,877,740,1097,20270,10208,563,6,194.0,34.0,234
614,129600,Photo,3,7,6,5,0.0,5292,9321,756,646,1033,5867,3404,516,6,226.0,42.0,274
615,129600,Status,2,7,5,12,1.0,15576,27513,2417,2327,3098,19078,10840,1839,11,238.0,51.0,300
616,129600,Photo,3,7,5,3,0.0,54256,82011,1620,963,1419,42128,24224,977,10,755.0,58.0,823
617,129600,Photo,2,7,4,12,1.0,3726,6372,602,574,785,4760,2852,399,30,47.0,8.0,85
618,129600,Photo,1,7,4,6,1.0,31904,50539,863,770,1106,24010,12992,583,2,126.0,32.0,160
619,129600,Photo,1,7,3,13,1.0,40336,65309,1407,1330,2251,27771,14848,907,4,104.0,10.0,118
620,129600,Photo,2,7,3,1,0.0,4220,7774,685,597,838,4404,2326,407,10,167.0,26.0,203
621,129600,Photo,3,7,2,13,0.0,4666,8360,729,648,1014,5010,2818,459,9,152.0,41.0,202
622,129600,Photo,2,7,2,7,1.0,4274,7948,701,638,1020,5936,3164,460,0,128.0,15.0,143
623,129600,Photo,1,7,1,13,0.0,28208,41650,964,827,1237,18035,11120,636,13,234.0,43.0,290
624,128032,Photo,2,7,1,3,0.0,3330,5461,513,478,652,3675,2196,307,2,61.0,16.0,79
625,128032,Photo,2,7,7,11,1.0,3528,5918,550,513,787,4606,2660,360,0,66.0,9.0,75
626,128032,Photo,3,7,7,3,0.0,38576,55398,1355,890,1328,17365,12624,827,7,529.0,60.0,596
627,128032,Photo,3,7,6,13,1.0,2628,4264,528,503,652,3086,1846,328,3,42.0,10.0,55
628,128032,Photo,1,7,6,3,0.0,7232,12735,758,700,1236,8855,4712,471,2,75.0,24.0,101
629,128032,Status,2,7,5,10,0.0,10188,16978,1473,1441,2136,14450,8536,1395,13,61.0,13.0,87
630,128032,Photo,1,7,5,3,0.0,6408,11881,909,861,14974,7243,4040,490,26,162.0,7.0,195
631,128032,Photo,1,7,4,9,1.0,3414,6050,515,493,710,5005,2704,340,2,47.0,4.0,53
632,128032,Photo,2,7,4,5,1.0,53056,65260,2003,1412,2089,23679,17104,975,6,696.0,28.0,730
633,128032,Photo,1,7,3,10,1.0,66976,111502,1191,1054,1641,40203,19968,708,7,215.0,47.0,269

In [262]:
df3.shape

(634, 19)

# SORT DATA

In [263]:
df4 = df3.sort_values(by='like',ascending=False)

In [264]:
df4

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
244,130791,Photo,2,7,3,5,1.0,180480,319133,8072,4010,6242,108752,51456,3316,372,5172.0,790.0,6334
606,130791,Photo,2,7,3,5,1.0,180480,319133,8072,4010,6242,108752,51456,3316,372,5172.0,790.0,6334
379,111620,Photo,3,4,1,14,1.0,105632,147918,3984,2254,3391,48575,27328,1936,51,1998.0,128.0,2177
349,117764,Photo,3,5,5,13,0.0,81856,124753,3000,1637,2718,52477,27392,1756,45,1639.0,122.0,1806
168,135428,Photo,1,9,3,10,0.0,41984,68290,3370,2420,4074,34802,20928,2126,144,1622.0,208.0,1974
530,135428,Photo,1,9,3,10,0.0,41984,68290,3370,2420,4074,34802,20928,2126,144,1622.0,208.0,1974
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
460,92507,Photo,3,2,1,13,0.0,55520,665792,4544,3586,6624,648611,47488,3430,146,1546.0,181.0,1873
101,137020,Photo,2,10,4,3,0.0,68896,104952,2624,1326,1952,35707,19840,1354,26,1505.0,95.0,1626
323,123047,Photo,3,6,1,10,0.0,56672,104966,2579,1334,1850,78678,37408,1831,20,1372.0,47.0,1439
561,132817,Photo,3,8,4,10,0.0,33536,64850,1954,1016,1678,50076,24448,1564,33,1155.0,102.0,1290
199,132817,Photo,3,8,4,10,0.0,33536,64850,1954,1016,1678,50076,24448,1564,33,1155.0,102.0,1290
538,135195,Photo,3,9,6,3,1.0,22304,37159,1805,984,1618,22864,13304,1349,29,1047.0,98.0,1174
176,135195,Photo,3,9,6,3,1.0,22304,37159,1805,984,1618,22864,13304,1349,29,1047.0,98.0,1174
105,137020,Photo,1,10,2,4,0.0,70144,111745,3216,2628,4782,43671,20608,1542,42,955.0,139.0,1136
504,136013,Status,2,10,3,2,1.0,31136,59964,6164,5934,9237,35977,18048,4376,60,859.0,90.0,1009
142,136013,Status,2,10,3,2,1.0,31136,59964,6164,5934,9237,35977,18048,4376,60,859.0,90.0,1009
568,132201,Photo,1,8,1,3,0.0,50640,121234,2240,1577,2779,92348,34880,1790,4,859.0,68.0,931
206,132201,Photo,1,8,1,3,0.0,50640,121234,2240,1577,2779,92348,34880,1790,4,859.0,68.0,931
346,117764,Photo,3,5,7,2,0.0,38960,65149,2298,1702,3000,57722,34368,1978,37,821.0,90.0,948
191,133679,Photo,3,8,1,10,0.0,19648,33643,1359,695,990,24034,13528,1020,9,766.0,43.0,818
553,133679,Photo,3,8,1,10,0.0,19648,33643,1359,695,990,24034,13528,1020,9,766.0,43.0,818
391,109670,Photo,2,4,1,13,1.0,32208,55696,1933,1367,2123,43980,24720,1568,6,766.0,109.0,881
616,129600,Photo,3,7,5,3,0.0,54256,82011,1620,963,1419,42128,24224,977,10,755.0,58.0,823
254,129600,Photo,3,7,5,3,0.0,54256,82011,1620,963,1419,42128,24224,977,10,755.0,58.0,823
67,138185,Photo,1,11,7,3,1.0,53456,93790,1576,995,1469,32646,14912,884,20,697.0,70.0,787
270,128032,Photo,2,7,4,5,1.0,53056,65260,2003,1412,2089,23679,17104,975,6,696.0,28.0,730
632,128032,Photo,2,7,4,5,1.0,53056,65260,2003,1412,2089,23679,17104,975,6,696.0,28.0,730
17,138414,Photo,1,12,2,12,1.0,53264,111785,1706,1103,1655,92512,39776,1307,15,678.0,20.0,713
442,98195,Photo,3,3,4,13,0.0,34480,191207,1591,1156,1926,184270,30720,1292,10,664.0,97.0,771
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
133,136393,Photo,1,10,6,8,0.0,652,1331,214,206,249,1249,588,182,0,11.0,1.0,12
127,136393,Photo,1,10,6,13,0.0,747,1443,226,220,287,1252,632,194,0,9.0,1.0,10
130,136393,Photo,1,10,6,11,0.0,910,1673,207,201,247,1503,782,176,0,8.0,2.0,10
118,136642,Photo,1,10,7,10,0.0,834,1570,399,392,510,1390,704,351,0,7.0,2.0,9
117,136642,Photo,1,10,7,11,0.0,729,1374,303,298,331,1284,650,262,0,7.0,0.0,7
125,136393,Photo,1,10,7,5,0.0,677,1240,236,228,264,1098,580,196,0,7.0,2.0,9
132,136393,Photo,1,10,6,9,0.0,659,1158,199,194,239,1041,576,169,1,7.0,2.0,10
131,136393,Photo,1,10,6,9,0.0,3906,8239,868,863,2632,7736,3768,774,0,7.0,3.0,10
124,136393,Photo,1,10,7,6,0.0,677,1285,251,246,297,1210,615,211,0,7.0,NaN,7
119,136393,Photo,1,10,7,10,0.0,786,1573,263,257,318,1401,660,222,0,6.0,2.0,8
430,100732,Link,1,3,7,14,0.0,2933,5144,24,23,26,3972,2012,19,0,6.0,0.0,6
426,100732,Photo,1,3,7,18,0.0,391,746,131,130,766,723,380,93,0,6.0,1.0,7
481,86491,Link,1,1,4,4,1.0,4938,7910,66,63,70,6625,3804,59,0,5.0,2.0,7
128,136393,Photo,1,10,6,13,0.0,645,1117,195,192,224,989,554,166,0,4.0,1.0,5
115,136642,Photo,1,10,7,12,1.0,813,1568,323,319,387,1402,695,280,0,4.0,2.0,6
431,100732,Photo,1,3,7,12,0.0,4094,7469,206,203,1420,7451,4088,200,0,4.0,0.0,4
432,100732,Photo,1,3,6,17,0.0,452,726,186,184,889,721,450,114,0,4.0,1.0,5
429,100732,Photo,1,3,7,15,0.0,3772,6971,144,144,1033,6932,3758,140,0,3.0,0.0,3
129,136393,Photo,1,10,6,12,0.0,754,1510,206,205,252,1430,690,175,0,3.0,0.0,3
123,136393,Photo,1,10,7,7,0.0,617,1071,229,223,265,935,521,191,1,3.0,2.0,6
120,136393,Photo,1,10,7,9,0.0,584,1029,273,271,308,943,511,232,0,2.0,NaN,2
428,100732,Photo,1,3,7,15,0.0,5132,9067,398,398,1690,9065,5132,393,0,2.0,0.0,2
422,102112,Photo,1,3,1,19,0.0,238,570,143,142,834,567,236,99,0,2.0,0.0,2
122,136393,Photo,1,10,7,8,0.0,619,1096,257,254,292,951,516,217,1,1.0,2.0,4
100,137020,Photo,1,10,4,9,1.0,1357,2453,37,37,55,2154,1120,32,0,0.0,0.0,0
21,138414,Photo,1,12,7,10,0.0,1384,2467,15,15,20,2196,1172,15,0,0.0,0.0,0
76,137893,Photo,1,11,3,2,0.0,1228,2392,17,17,19,2392,1228,17,0,0.0,0.0,0
417,104070,Photo,1,3,3,10,0.0,1874,2474,25,25,31,1483,1062,15,0,0.0,0.0,0
441,98195,Photo,1,3,5,4,1.0,1845,2670,9,9,9,1614,1008,9,0,0.0,0.0,0
111,136736,Photo,1,10,6,8,0.0,1261,2158,37,37,49,1911,1077,33,0,NaN,NaN,0

In [265]:
df4 = df3.sort_values(by='Lifetime Post Consumptions',ascending=True)

In [266]:
df4

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
441,98195,Photo,1,3,5,4,1.0,1845,2670,9,9,9,1614,1008,9,0,0.0,0.0,0
76,137893,Photo,1,11,3,2,0.0,1228,2392,17,17,19,2392,1228,17,0,0.0,0.0,0
21,138414,Photo,1,12,7,10,0.0,1384,2467,15,15,20,2196,1172,15,0,0.0,0.0,0
430,100732,Link,1,3,7,14,0.0,2933,5144,24,23,26,3972,2012,19,0,6.0,0.0,6
417,104070,Photo,1,3,3,10,0.0,1874,2474,25,25,31,1483,1062,15,0,0.0,0.0,0
111,136736,Photo,1,10,6,8,0.0,1261,2158,37,37,49,1911,1077,33,0,NaN,NaN,0
100,137020,Photo,1,10,4,9,1.0,1357,2453,37,37,55,2154,1120,32,0,0.0,0.0,0
481,86491,Link,1,1,4,4,1.0,4938,7910,66,63,70,6625,3804,59,0,5.0,2.0,7
485,86491,Link,1,1,2,2,0.0,5168,8371,66,59,71,7041,3996,58,0,12.0,2.0,14
50,138353,Photo,2,11,1,9,0.0,1728,3155,108,65,95,2313,1232,77,1,48.0,9.0,58
438,98195,Link,2,3,6,6,0.0,5730,10083,103,71,97,8964,4830,92,2,32.0,15.0,49
49,138353,Link,1,12,2,2,0.0,1536,3094,84,76,99,2903,1407,76,1,12.0,1.0,14
19,138414,Photo,3,12,1,11,0.0,1591,2825,121,88,111,2116,1161,100,0,34.0,8.0,42
18,138414,Status,3,12,2,3,0.0,3930,7509,130,86,112,5009,2410,101,4,54.0,17.0,75
149,135713,Link,1,10,6,11,1.0,3616,6887,111,90,118,4263,2138,93,0,24.0,11.0,35
511,135713,Link,1,10,6,11,1.0,3616,6887,111,90,118,4263,2138,93,0,24.0,11.0,35
47,138353,Link,1,12,3,2,0.0,1925,3481,97,83,126,2307,1180,77,6,18.0,8.0,32
235,131300,Status,2,7,7,10,0.0,10956,19279,128,119,130,18838,10564,123,3,13.0,1.0,17
597,131300,Status,2,7,7,10,0.0,10956,19279,128,119,130,18838,10564,123,3,13.0,1.0,17
22,138414,Link,1,12,7,10,0.0,3454,6853,118,104,130,6282,3100,106,0,16.0,2.0,18
12,139441,Photo,2,12,5,10,0.0,2847,5133,193,115,133,3779,2072,152,0,90.0,14.0,104
84,137177,Status,3,11,5,2,0.0,6692,13092,199,108,141,7549,3336,156,2,99.0,16.0,117
23,138414,Photo,3,12,7,3,0.0,2723,4888,176,118,143,2964,1621,143,0,72.0,24.0,96
11,139441,Photo,2,12,5,10,0.0,3112,5590,208,127,145,3887,2174,165,0,88.0,18.0,106
16,138414,Photo,3,12,3,3,0.0,1722,2981,163,123,148,1868,1050,123,2,40.0,12.0,54
27,138458,Photo,3,12,5,3,0.0,2478,4306,212,124,149,2612,1443,166,0,100.0,17.0,117
232,131630,Status,2,7,2,6,1.0,10824,20573,135,126,153,20030,10384,126,6,14.0,1.0,21
594,131630,Status,2,7,2,6,1.0,10824,20573,135,126,153,20030,10384,126,6,14.0,1.0,21
2,139441,Photo,3,12,3,3,0.0,2413,4373,177,113,154,2812,1503,132,0,66.0,14.0,80
0,139441,Photo,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640,119,4,79.0,17.0,100
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46,138353,Status,1,12,3,11,0.0,16576,30612,3572,3464,4802,24363,12888,3014,4,174.0,36.0,214
279,126345,Photo,1,6,2,3,0.0,109056,191324,2552,2457,4906,48765,25024,1353,7,148.0,39.0,194
223,131808,Status,2,8,6,10,1.0,20168,35904,3370,3244,5106,26881,15056,2806,18,332.0,54.0,404
585,131808,Status,2,8,6,10,1.0,20168,35904,3370,3244,5106,26881,15056,2806,18,332.0,54.0,404
172,135195,Status,2,9,1,10,0.0,21256,41906,4840,4754,5906,35455,17592,4318,38,163.0,27.0,228
534,135195,Status,2,9,1,10,0.0,21256,41906,4840,4754,5906,35455,17592,4318,38,163.0,27.0,228
604,130791,Status,2,7,4,6,0.0,17360,33613,2573,2448,6017,23338,11800,1905,9,484.0,79.0,572
242,130791,Status,2,7,4,6,0.0,17360,33613,2573,2448,6017,23338,11800,1905,9,484.0,79.0,572
244,130791,Photo,2,7,3,5,1.0,180480,319133,8072,4010,6242,108752,51456,3316,372,5172.0,790.0,6334
606,130791,Photo,2,7,3,5,1.0,180480,319133,8072,4010,6242,108752,51456,3316,372,5172.0,790.0,6334
38,138895,Status,2,12,7,9,0.0,17576,33058,5352,5202,6547,23135,11792,4104,11,227.0,31.0,269
371,113028,Status,2,4,6,3,1.0,17912,34774,2750,2567,6591,21009,11408,2256,17,447.0,123.0,587
460,92507,Photo,3,2,1,13,0.0,55520,665792,4544,3586,6624,648611,47488,3430,146,1546.0,181.0,1873
605,130791,Video,1,7,3,11,1.0,21872,40413,3872,3822,7327,24667,12920,2218,18,315.0,76.0,409
243,130791,Video,1,7,3,11,1.0,21872,40413,3872,3822,7327,24667,12920,2218,18,315.0,76.0,409
275,126424,Status,2,7,3,13,0.0,18320,31448,3742,3682,7854,25584,14920,3300,36,98.0,14.0,148
286,126141,Photo,1,6,5,11,1.0,2431,4180,389,383,7980,3963,2301,342,0,15.0,3.0,18
433,100732,Photo,1,3,6,17,0.0,11420,23855,1411,1342,8049,16634,8032,865,12,211.0,14.0,237
506,136013,Photo,1,10,2,3,1.0,50736,140432,1462,1450,8308,46252,15552,1275,3,41.0,9.0,53
144,136013,Photo,1,10,2,3,1.0,50736,140432,1462,1450,8308,46252,15552,1275,3,41.0,9.0,53
424,102112,Photo,1,3,1,18,0.0,6400,11941,735,726,8415,10987,5916,628,0,32.0,6.0,38
142,136013,Status,2,10,3,2,1.0,31136,59964,6164,5934,9237,35977,18048,4376,60,859.0,90.0,1009
504,136013,Status,2,10,3,2,1.0,31136,59964,6164,5934,9237,35977,18048,4376,60,859.0,90.0,1009
436,100732,Photo,1,3,6,13,1.0,9604,16557,1061,1037,9614,13618,7984,705,16,127.0,0.0,143
427,100732,Photo,1,3,7,17,0.0,10844,22468,1409,1339,11064,18310,8848,1086,4,213.0,13.0,230
42,138353,Photo,1,12,5,10,0.0,7268,13989,2087,2079,12074,13544,7096,1975,7,26.0,3.0,36
268,128032,Photo,1,7,5,3,0.0,6408,11881,909,861,14974,7243,4040,490,26,162.0,7.0,195
630,128032,Photo,1,7,5,3,0.0,6408,11881,909,861,14974,7243,4040,490,26,162.0,7.0,195
446,96749,Photo,1,3,1,2,1.0,98816,125026,11452,11328,18115,16682,10336,1356,10,197.0,21.0,228
278,126345,Photo,1,6,2,9,1.0,5854,11854,1043,947,19779,5901,2894,583,11,202.0,5.0,218

In [267]:
df4.shape

(634, 19)

# TRANSPOSING DATA

In [268]:
df4 = df3.transpose()

In [269]:
df4

,0,1,2,3,4,5,6,7,8,9,...,624,625,626,627,628,629,630,631,632,633
Page total likes,139441,139441,139441,139441,139441,139441,139441,139441,139441,139441,...,128032,128032,128032,128032,128032,128032,128032,128032,128032,128032
Type,Photo,Status,Photo,Photo,Photo,Status,Photo,Photo,Status,Photo,...,Photo,Photo,Photo,Photo,Photo,Status,Photo,Photo,Photo,Photo
Category,2,2,3,2,2,2,3,3,2,3,...,2,2,3,3,1,2,1,1,2,1
Post Month,12,12,12,12,12,12,12,12,12,12,...,7,7,7,7,7,7,7,7,7,7
Post Weekday,4,3,3,2,2,1,1,7,7,6,...,1,7,7,6,6,5,5,4,4,3
Post Hour,3,10,3,10,3,9,3,9,3,10,...,3,11,3,13,3,10,3,9,5,10
Paid,0,0,0,1,0,0,1,1,0,0,...,0,1,0,1,0,0,0,1,1,1
Lifetime Post Total Reach,2752,10460,2413,50128,7244,10472,11692,13720,11844,4694,...,3330,3528,38576,2628,7232,10188,6408,3414,53056,66976
Lifetime Post Total Impressions,5091,19057,4373,87991,13594,20849,19479,24137,22538,8668,...,5461,5918,55398,4264,12735,16978,11881,6050,65260,111502
Lifetime Engaged Users,178,1457,177,2211,671,1191,481,537,1530,280,...,513,550,1355,528,758,1473,909,515,2003,1191
Lifetime Post Consumers,109,1361,113,790,410,1073,265,232,1407,183,...,478,513,890,503,700,1441,861,493,1412,1054
Lifetime Post Consumptions,159,1674,154,1119,580,1389,364,305,1692,250,...,652,787,1328,652,1236,2136,14974,710,2089,1641
Lifetime Post Impressions by people who have liked your Page,3078,11710,2812,61027,6228,16034,15432,19728,15220,4309,...,3675,4606,17365,3086,8855,14450,7243,5005,23679,40203
Lifetime Post reach by people who like your Page,1640,6112,1503,32048,3200,7852,9328,11056,7912,2324,...,2196,2660,12624,1846,4712,8536,4040,2704,17104,19968
Lifetime People who have liked your Page and engaged with your post,119,1108,132,1386,396,1016,379,422,1250,199,...,307,360,827,328,471,1395,490,340,975,708
comment,4,5,0,58,19,1,3,0,0,3,...,2,0,7,3,2,13,26,2,6,7
like,79,130,66,1572,325,152,249,325,161,113,...,61,66,529,42,75,61,162,47,696,215
share,17,29,14,147,49,33,27,14,31,26,...,16,9,60,10,24,13,7,4,28,47
Total Interactions,100,164,80,1777,393,186,279,339,192,142,...,79,75,596,55,101,87,195,53,730,269

# MELTING DATA TO LONG FORMAT

In [270]:
df3

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,139441,Photo,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640,119,4,79.0,17.0,100
1,139441,Status,2,12,3,10,0.0,10460,19057,1457,1361,1674,11710,6112,1108,5,130.0,29.0,164
2,139441,Photo,3,12,3,3,0.0,2413,4373,177,113,154,2812,1503,132,0,66.0,14.0,80
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
4,139441,Photo,2,12,2,3,0.0,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393
5,139441,Status,2,12,1,9,0.0,10472,20849,1191,1073,1389,16034,7852,1016,1,152.0,33.0,186
6,139441,Photo,3,12,1,3,1.0,11692,19479,481,265,364,15432,9328,379,3,249.0,27.0,279
7,139441,Photo,3,12,7,9,1.0,13720,24137,537,232,305,19728,11056,422,0,325.0,14.0,339
8,139441,Status,2,12,7,3,0.0,11844,22538,1530,1407,1692,15220,7912,1250,0,161.0,31.0,192
9,139441,Photo,3,12,6,10,0.0,4694,8668,280,183,250,4309,2324,199,3,113.0,26.0,142
10,139441,Status,2,12,5,10,0.0,21744,42334,4258,4100,4540,37849,18952,3798,0,233.0,19.0,252
11,139441,Photo,2,12,5,10,0.0,3112,5590,208,127,145,3887,2174,165,0,88.0,18.0,106
12,139441,Photo,2,12,5,10,0.0,2847,5133,193,115,133,3779,2072,152,0,90.0,14.0,104
13,139441,Photo,2,12,5,3,0.0,2549,4896,249,134,168,3631,1917,183,5,137.0,10.0,152
14,138414,Photo,2,12,4,5,1.0,22784,39941,887,337,417,34415,19312,684,2,577.0,20.0,599
15,138414,Status,2,12,3,10,0.0,10060,19680,1264,1209,1425,17272,8548,1162,4,86.0,18.0,108
16,138414,Photo,3,12,3,3,0.0,1722,2981,163,123,148,1868,1050,123,2,40.0,12.0,54
17,138414,Photo,1,12,2,12,1.0,53264,111785,1706,1103,1655,92512,39776,1307,15,678.0,20.0,713
18,138414,Status,3,12,2,3,0.0,3930,7509,130,86,112,5009,2410,101,4,54.0,17.0,75
19,138414,Photo,3,12,1,11,0.0,1591,2825,121,88,111,2116,1161,100,0,34.0,8.0,42
20,138414,Photo,2,12,1,3,0.0,2848,5066,200,142,184,3561,1963,157,3,66.0,12.0,81
21,138414,Photo,1,12,7,10,0.0,1384,2467,15,15,20,2196,1172,15,0,0.0,0.0,0
22,138414,Link,1,12,7,10,0.0,3454,6853,118,104,130,6282,3100,106,0,16.0,2.0,18
23,138414,Photo,3,12,7,3,0.0,2723,4888,176,118,143,2964,1621,143,0,72.0,24.0,96
24,138414,Status,2,12,6,10,0.0,8488,15294,1341,1270,1489,9684,5244,995,3,99.0,19.0,121
25,138458,Status,2,12,6,3,0.0,8284,15104,1521,1462,1711,10266,5372,1200,0,88.0,18.0,106
26,138458,Status,2,12,5,11,0.0,19552,34143,2806,2531,3420,17748,9824,1779,10,412.0,72.0,494
27,138458,Photo,3,12,5,3,0.0,2478,4306,212,124,149,2612,1443,166,0,100.0,17.0,117
28,138895,Photo,2,12,5,3,0.0,9560,18264,973,559,885,9217,4748,621,36,523.0,63.0,622
29,138895,Video,1,12,4,11,1.0,36208,61262,1141,1068,1728,30131,14112,559,18,143.0,13.0,174
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
604,130791,Status,2,7,4,6,0.0,17360,33613,2573,2448,6017,23338,11800,1905,9,484.0,79.0,572
605,130791,Video,1,7,3,11,1.0,21872,40413,3872,3822,7327,24667,12920,2218,18,315.0,76.0,409
606,130791,Photo,2,7,3,5,1.0,180480,319133,8072,4010,6242,108752,51456,3316,372,5172.0,790.0,6334
607,130791,Photo,1,7,2,13,0.0,44464,66824,1052,930,1571,22904,14080,559,4,154.0,30.0,188
608,130791,Photo,2,7,2,8,0.0,2881,5188,550,503,730,3840,2040,323,0,73.0,15.0,88
609,129600,Photo,2,7,1,12,0.0,3460,6503,541,482,667,4371,2260,314,0,96.0,19.0,115
610,129600,Photo,3,7,1,6,0.0,3406,5656,571,512,731,4446,2598,355,1,98.0,19.0,118
611,129600,Photo,2,7,7,11,1.0,2602,4349,479,444,588,3342,1946,287,1,53.0,14.0,68
612,129600,Photo,1,7,7,6,1.0,5848,9068,622,570,795,6651,4212,383,4,71.0,10.0,85
613,129600,Photo,1,7,6,11,0.0,26944,43464,877,740,1097,20270,10208,563,6,194.0,34.0,234
614,129600,Photo,3,7,6,5,0.0,5292,9321,756,646,1033,5867,3404,516,6,226.0,42.0,274
615,129600,Status,2,7,5,12,1.0,15576,27513,2417,2327,3098,19078,10840,1839,11,238.0,51.0,300
616,129600,Photo,3,7,5,3,0.0,54256,82011,1620,963,1419,42128,24224,977,10,755.0,58.0,823
617,129600,Photo,2,7,4,12,1.0,3726,6372,602,574,785,4760,2852,399,30,47.0,8.0,85
618,129600,Photo,1,7,4,6,1.0,31904,50539,863,770,1106,24010,12992,583,2,126.0,32.0,160
619,129600,Photo,1,7,3,13,1.0,40336,65309,1407,1330,2251,27771,14848,907,4,104.0,10.0,118
620,129600,Photo,2,7,3,1,0.0,4220,7774,685,597,838,4404,2326,407,10,167.0,26.0,203
621,129600,Photo,3,7,2,13,0.0,4666,8360,729,648,1014,5010,2818,459,9,152.0,41.0,202
622,129600,Photo,2,7,2,7,1.0,4274,7948,701,638,1020,5936,3164,460,0,128.0,15.0,143
623,129600,Photo,1,7,1,13,0.0,28208,41650,964,827,1237,18035,11120,636,13,234.0,43.0,290
624,128032,Photo,2,7,1,3,0.0,3330,5461,513,478,652,3675,2196,307,2,61.0,16.0,79
625,128032,Photo,2,7,7,11,1.0,3528,5918,550,513,787,4606,2660,360,0,66.0,9.0,75
626,128032,Photo,3,7,7,3,0.0,38576,55398,1355,890,1328,17365,12624,827,7,529.0,60.0,596
627,128032,Photo,3,7,6,13,1.0,2628,4264,528,503,652,3086,1846,328,3,42.0,10.0,55
628,128032,Photo,1,7,6,3,0.0,7232,12735,758,700,1236,8855,4712,471,2,75.0,24.0,101
629,128032,Status,2,7,5,10,0.0,10188,16978,1473,1441,2136,14450,8536,1395,13,61.0,13.0,87
630,128032,Photo,1,7,5,3,0.0,6408,11881,909,861,14974,7243,4040,490,26,162.0,7.0,195
631,128032,Photo,1,7,4,9,1.0,3414,6050,515,493,710,5005,2704,340,2,47.0,4.0,53
632,128032,Photo,2,7,4,5,1.0,53056,65260,2003,1412,2089,23679,17104,975,6,696.0,28.0,730
633,128032,Photo,1,7,3,10,1.0,66976,111502,1191,1054,1641,40203,19968,708,7,215.0,47.0,269

In [271]:
df4 = df3.melt()

In [272]:
for var in df4['variable'].unique():
    print(var)

Page total likes
Type
Category
Post Month
Post Weekday
Post Hour
Paid
Lifetime Post Total Reach
Lifetime Post Total Impressions
Lifetime Engaged Users
Lifetime Post Consumers
Lifetime Post Consumptions
Lifetime Post Impressions by people who have liked your Page
Lifetime Post reach by people who like your Page
Lifetime People who have liked your Page and engaged with your post
comment
like
share
Total Interactions

In [273]:
df4

                 variable   value
0        Page total likes  139441
1        Page total likes  139441
2        Page total likes  139441
3        Page total likes  139441
4        Page total likes  139441
5        Page total likes  139441
6        Page total likes  139441
7        Page total likes  139441
8        Page total likes  139441
9        Page total likes  139441
10       Page total likes  139441
11       Page total likes  139441
12       Page total likes  139441
13       Page total likes  139441
14       Page total likes  138414
15       Page total likes  138414
16       Page total likes  138414
17       Page total likes  138414
18       Page total likes  138414
19       Page total likes  138414
20       Page total likes  138414
21       Page total likes  138414
22       Page total likes  138414
23       Page total likes  138414
24       Page total likes  138414
25       Page total likes  138458
26       Page total likes  138458
27       Page total likes  138458
28       Page total likes  138895
29       Page total likes  138895
...                   ...     ...
12016  Total Interactions     572
12017  Total Interactions     409
12018  Total Interactions    6334
12019  Total Interactions     188
12020  Total Interactions      88
12021  Total Interactions     115
12022  Total Interactions     118
12023  Total Interactions      68
12024  Total Interactions      85
12025  Total Interactions     234
12026  Total Interactions     274
12027  Total Interactions     300
12028  Total Interactions     823
12029  Total Interactions      85
12030  Total Interactions     160
12031  Total Interactions     118
12032  Total Interactions     203
12033  Total Interactions     202
12034  Total Interactions     143
12035  Total Interactions     290
12036  Total Interactions      79
12037  Total Interactions      75
12038  Total Interactions     596
12039  Total Interactions      55
12040  Total Interactions     101
12041  Total Interactions      87
12042  Total Interactions     195
12043  Total Interactions      53
12044  Total Interactions     730
12045  Total Interactions     269

[12046 rows x 2 columns]

In [274]:
df4.shape

(12046, 2)

In [397]:
df4 = df3.melt(id_vars=['Type'],value_vars=['Category','Lifetime Post Consumers'],
               var_name='VARIABLE',value_name='VALUE')

In [398]:
df4

        Type                 VARIABLE  VALUE
0      Photo                 Category      2
1     Status                 Category      2
2      Photo                 Category      3
3      Photo                 Category      2
4      Photo                 Category      2
5     Status                 Category      2
6      Photo                 Category      3
7      Photo                 Category      3
8     Status                 Category      2
9      Photo                 Category      3
10    Status                 Category      2
11     Photo                 Category      2
12     Photo                 Category      2
13     Photo                 Category      2
14     Photo                 Category      2
15    Status                 Category      2
16     Photo                 Category      3
17     Photo                 Category      1
18    Status                 Category      3
19     Photo                 Category      3
20     Photo                 Category      2
21     Photo                 Category      1
22      Link                 Category      1
23     Photo                 Category      3
24    Status                 Category      2
25    Status                 Category      2
26    Status                 Category      2
27     Photo                 Category      3
28     Photo                 Category      2
29     Video                 Category      1
...      ...                      ...    ...
1238  Status  Lifetime Post Consumers   2448
1239   Video  Lifetime Post Consumers   3822
1240   Photo  Lifetime Post Consumers   4010
1241   Photo  Lifetime Post Consumers    930
1242   Photo  Lifetime Post Consumers    503
1243   Photo  Lifetime Post Consumers    482
1244   Photo  Lifetime Post Consumers    512
1245   Photo  Lifetime Post Consumers    444
1246   Photo  Lifetime Post Consumers    570
1247   Photo  Lifetime Post Consumers    740
1248   Photo  Lifetime Post Consumers    646
1249  Status  Lifetime Post Consumers   2327
1250   Photo  Lifetime Post Consumers    963
1251   Photo  Lifetime Post Consumers    574
1252   Photo  Lifetime Post Consumers    770
1253   Photo  Lifetime Post Consumers   1330
1254   Photo  Lifetime Post Consumers    597
1255   Photo  Lifetime Post Consumers    648
1256   Photo  Lifetime Post Consumers    638
1257   Photo  Lifetime Post Consumers    827
1258   Photo  Lifetime Post Consumers    478
1259   Photo  Lifetime Post Consumers    513
1260   Photo  Lifetime Post Consumers    890
1261   Photo  Lifetime Post Consumers    503
1262   Photo  Lifetime Post Consumers    700
1263  Status  Lifetime Post Consumers   1441
1264   Photo  Lifetime Post Consumers    861
1265   Photo  Lifetime Post Consumers    493
1266   Photo  Lifetime Post Consumers   1412
1267   Photo  Lifetime Post Consumers   1054

[1268 rows x 3 columns]

In [399]:
df4.shape

(1268, 3)

# Casting Data To Wide Format

In [426]:
df3

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,139441,Photo,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640,119,4,79.0,17.0,100
1,139441,Status,2,12,3,10,0.0,10460,19057,1457,1361,1674,11710,6112,1108,5,130.0,29.0,164
2,139441,Photo,3,12,3,3,0.0,2413,4373,177,113,154,2812,1503,132,0,66.0,14.0,80
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
4,139441,Photo,2,12,2,3,0.0,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393
5,139441,Status,2,12,1,9,0.0,10472,20849,1191,1073,1389,16034,7852,1016,1,152.0,33.0,186
6,139441,Photo,3,12,1,3,1.0,11692,19479,481,265,364,15432,9328,379,3,249.0,27.0,279
7,139441,Photo,3,12,7,9,1.0,13720,24137,537,232,305,19728,11056,422,0,325.0,14.0,339
8,139441,Status,2,12,7,3,0.0,11844,22538,1530,1407,1692,15220,7912,1250,0,161.0,31.0,192
9,139441,Photo,3,12,6,10,0.0,4694,8668,280,183,250,4309,2324,199,3,113.0,26.0,142
10,139441,Status,2,12,5,10,0.0,21744,42334,4258,4100,4540,37849,18952,3798,0,233.0,19.0,252
11,139441,Photo,2,12,5,10,0.0,3112,5590,208,127,145,3887,2174,165,0,88.0,18.0,106
12,139441,Photo,2,12,5,10,0.0,2847,5133,193,115,133,3779,2072,152,0,90.0,14.0,104
13,139441,Photo,2,12,5,3,0.0,2549,4896,249,134,168,3631,1917,183,5,137.0,10.0,152
14,138414,Photo,2,12,4,5,1.0,22784,39941,887,337,417,34415,19312,684,2,577.0,20.0,599
15,138414,Status,2,12,3,10,0.0,10060,19680,1264,1209,1425,17272,8548,1162,4,86.0,18.0,108
16,138414,Photo,3,12,3,3,0.0,1722,2981,163,123,148,1868,1050,123,2,40.0,12.0,54
17,138414,Photo,1,12,2,12,1.0,53264,111785,1706,1103,1655,92512,39776,1307,15,678.0,20.0,713
18,138414,Status,3,12,2,3,0.0,3930,7509,130,86,112,5009,2410,101,4,54.0,17.0,75
19,138414,Photo,3,12,1,11,0.0,1591,2825,121,88,111,2116,1161,100,0,34.0,8.0,42
20,138414,Photo,2,12,1,3,0.0,2848,5066,200,142,184,3561,1963,157,3,66.0,12.0,81
21,138414,Photo,1,12,7,10,0.0,1384,2467,15,15,20,2196,1172,15,0,0.0,0.0,0
22,138414,Link,1,12,7,10,0.0,3454,6853,118,104,130,6282,3100,106,0,16.0,2.0,18
23,138414,Photo,3,12,7,3,0.0,2723,4888,176,118,143,2964,1621,143,0,72.0,24.0,96
24,138414,Status,2,12,6,10,0.0,8488,15294,1341,1270,1489,9684,5244,995,3,99.0,19.0,121
25,138458,Status,2,12,6,3,0.0,8284,15104,1521,1462,1711,10266,5372,1200,0,88.0,18.0,106
26,138458,Status,2,12,5,11,0.0,19552,34143,2806,2531,3420,17748,9824,1779,10,412.0,72.0,494
27,138458,Photo,3,12,5,3,0.0,2478,4306,212,124,149,2612,1443,166,0,100.0,17.0,117
28,138895,Photo,2,12,5,3,0.0,9560,18264,973,559,885,9217,4748,621,36,523.0,63.0,622
29,138895,Video,1,12,4,11,1.0,36208,61262,1141,1068,1728,30131,14112,559,18,143.0,13.0,174
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
604,130791,Status,2,7,4,6,0.0,17360,33613,2573,2448,6017,23338,11800,1905,9,484.0,79.0,572
605,130791,Video,1,7,3,11,1.0,21872,40413,3872,3822,7327,24667,12920,2218,18,315.0,76.0,409
606,130791,Photo,2,7,3,5,1.0,180480,319133,8072,4010,6242,108752,51456,3316,372,5172.0,790.0,6334
607,130791,Photo,1,7,2,13,0.0,44464,66824,1052,930,1571,22904,14080,559,4,154.0,30.0,188
608,130791,Photo,2,7,2,8,0.0,2881,5188,550,503,730,3840,2040,323,0,73.0,15.0,88
609,129600,Photo,2,7,1,12,0.0,3460,6503,541,482,667,4371,2260,314,0,96.0,19.0,115
610,129600,Photo,3,7,1,6,0.0,3406,5656,571,512,731,4446,2598,355,1,98.0,19.0,118
611,129600,Photo,2,7,7,11,1.0,2602,4349,479,444,588,3342,1946,287,1,53.0,14.0,68
612,129600,Photo,1,7,7,6,1.0,5848,9068,622,570,795,6651,4212,383,4,71.0,10.0,85
613,129600,Photo,1,7,6,11,0.0,26944,43464,877,740,1097,20270,10208,563,6,194.0,34.0,234
614,129600,Photo,3,7,6,5,0.0,5292,9321,756,646,1033,5867,3404,516,6,226.0,42.0,274
615,129600,Status,2,7,5,12,1.0,15576,27513,2417,2327,3098,19078,10840,1839,11,238.0,51.0,300
616,129600,Photo,3,7,5,3,0.0,54256,82011,1620,963,1419,42128,24224,977,10,755.0,58.0,823
617,129600,Photo,2,7,4,12,1.0,3726,6372,602,574,785,4760,2852,399,30,47.0,8.0,85
618,129600,Photo,1,7,4,6,1.0,31904,50539,863,770,1106,24010,12992,583,2,126.0,32.0,160
619,129600,Photo,1,7,3,13,1.0,40336,65309,1407,1330,2251,27771,14848,907,4,104.0,10.0,118
620,129600,Photo,2,7,3,1,0.0,4220,7774,685,597,838,4404,2326,407,10,167.0,26.0,203
621,129600,Photo,3,7,2,13,0.0,4666,8360,729,648,1014,5010,2818,459,9,152.0,41.0,202
622,129600,Photo,2,7,2,7,1.0,4274,7948,701,638,1020,5936,3164,460,0,128.0,15.0,143
623,129600,Photo,1,7,1,13,0.0,28208,41650,964,827,1237,18035,11120,636,13,234.0,43.0,290
624,128032,Photo,2,7,1,3,0.0,3330,5461,513,478,652,3675,2196,307,2,61.0,16.0,79
625,128032,Photo,2,7,7,11,1.0,3528,5918,550,513,787,4606,2660,360,0,66.0,9.0,75
626,128032,Photo,3,7,7,3,0.0,38576,55398,1355,890,1328,17365,12624,827,7,529.0,60.0,596
627,128032,Photo,3,7,6,13,1.0,2628,4264,528,503,652,3086,1846,328,3,42.0,10.0,55
628,128032,Photo,1,7,6,3,0.0,7232,12735,758,700,1236,8855,4712,471,2,75.0,24.0,101
629,128032,Status,2,7,5,10,0.0,10188,16978,1473,1441,2136,14450,8536,1395,13,61.0,13.0,87
630,128032,Photo,1,7,5,3,0.0,6408,11881,909,861,14974,7243,4040,490,26,162.0,7.0,195
631,128032,Photo,1,7,4,9,1.0,3414,6050,515,493,710,5005,2704,340,2,47.0,4.0,53
632,128032,Photo,2,7,4,5,1.0,53056,65260,2003,1412,2089,23679,17104,975,6,696.0,28.0,730
633,128032,Photo,1,7,3,10,1.0,66976,111502,1191,1054,1641,40203,19968,708,7,215.0,47.0,269

In [455]:
df4 = df3.iloc[[0,1,2],[1,2,7]]

In [459]:
df4

     Type  Category  Lifetime Post Total Reach
0   Photo         2                       2752
1  Status         2                      10460
2   Photo         3                       2413

In [456]:
df4.drop_duplicates(inplace=True)

In [457]:
df4.reset_index(drop=True, inplace=True)

In [458]:
df4.pivot(index='Type',columns='Category',values='Lifetime Post Total Reach')

Category        2       3
Type
Photo      2752.0  2413.0
Status    10460.0     NaN